# Generated by Django 5.0.6 on 2024-07-12 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='blood_type',
            new_name='Hours_Worked_per_Week',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='civil_status',
            new_name='Job_Title',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='college',
            new_name='Student_status',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='company_name',
            new_name='Work_Location',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='elementary',
            new_name='Work_schedule',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='father_middle',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='father_surname',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='graduate_studies',
            new_name='father_first_name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='height',
            new_name='father_middle_name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='mother_first',
            new_name='father_sname_name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='mother_middle',
            new_name='gwa',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='mother_surname',
            new_name='mother_first_name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='name_of_children',
            new_name='mother_middle_name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='occupation',
            new_name='mother_sname_name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='religion',
            new_name='school',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='secondary',
            new_name='units',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='sss_number',
            new_name='zip_code',
        ),
        migrations.RemoveField(
            model_name='item',
            name='vocational_course',
        ),
        migrations.RemoveField(
            model_name='item',
            name='weight',
        ),
    ]
