# Generated by Django 5.0.6 on 2024-07-12 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_item_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='father_sname_name',
            new_name='father_sname',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='mother_sname_name',
            new_name='mother_sname',
        ),
    ]
