# Generated by Django 5.0.6 on 2024-07-16 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_father_sname_name_item_father_sname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Hours_Worked_per_Week',
            new_name='Agency_Employee_number',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Job_Title',
            new_name='College',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Student_status',
            new_name='Date_of_birthday',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Work_Location',
            new_name='Elementary',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Work_schedule',
            new_name='Height',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='gwa',
            new_name='SSS_number',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='birthday',
            new_name='Secondary',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='company',
            new_name='TIN_number',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='course',
            new_name='Weight',
        ),
        migrations.RemoveField(
            model_name='item',
            name='school',
        ),
        migrations.RemoveField(
            model_name='item',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='item',
            name='units',
        ),
    ]
