# Generated by Django 5.0.6 on 2024-07-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_hours_worked_per_week_item_agency_employee_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='father_first_name',
            new_name='Father_first_name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='father_middle_name',
            new_name='Father_middle_name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='father_sname',
            new_name='Father_sname',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='first_name',
            new_name='First_name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='mother_first_name',
            new_name='Mother_first_name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='mother_middle_name',
            new_name='Mother_middle_name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='mother_sname',
            new_name='Mother_sname',
        ),
        migrations.AlterField(
            model_name='item',
            name='Agency_Employee_number',
            field=models.FloatField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='Date_of_birthday',
            field=models.DateField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='Height',
            field=models.FloatField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='SSS_number',
            field=models.FloatField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='TIN_number',
            field=models.FloatField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='Weight',
            field=models.FloatField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='contact_number',
            field=models.FloatField(default='', max_length=15),
        ),
    ]
