# Generated by Django 5.0.6 on 2024-07-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_father_first_name_item_father_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='College',
            new_name='college',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Elementary',
            new_name='elementary',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Father_first_name',
            new_name='father_first_name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Father_middle_name',
            new_name='father_middle_name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Father_sname',
            new_name='father_surname',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='First_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Mother_first_name',
            new_name='mother_first_name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Mother_middle_name',
            new_name='mother_middle_name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Mother_sname',
            new_name='mother_surname',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Secondary',
            new_name='secondary',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Agency_Employee_number',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Date_of_birthday',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Height',
        ),
        migrations.RemoveField(
            model_name='item',
            name='SSS_number',
        ),
        migrations.RemoveField(
            model_name='item',
            name='TIN_number',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Weight',
        ),
        migrations.AddField(
            model_name='item',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='contact_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='item',
            name='sex',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='zip_code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='item',
            name='agency_employee_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='height',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='item',
            name='sss_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='tin_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
    ]
