# Generated by Django 5.0.6 on 2024-07-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_college_item_college_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='civil_status',
            field=models.CharField(default='', max_length=20),
        ),
    ]
